(deftheme my-rails-casts
  "Created 2013-11-06.")

(custom-theme-set-faces
 'my-rails-casts
 '(cursor ((t (:background "#ffffff" :foreground "#000000"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#ffffff"))))
 '(highlight ((t (:background "#333435"))))
 '(region ((t (:background "#555577"))))
 '(secondary-selection ((t (:background "darkslateblue"))))
 '(trailing-whitespace ((t (:background "light salmon"))))
 '(font-lock-builtin-face ((t (:foreground "#D0D0FF"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#BC9458" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#6d9cbe"))))
 '(font-lock-doc-face ((t (:foreground "#a5c261"))))
 '(font-lock-function-name-face ((t (:foreground "#ffc66d"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#cc7833"))))
 '(font-lock-preprocessor-face ((t (:foreground "#cc7833"))))
 '(font-lock-string-face ((t (:foreground "#a5c261"))))
 '(font-lock-type-face ((t (:foreground "white"))))
 '(font-lock-variable-name-face ((t (:foreground "LightSteelBlue"))))
 '(font-lock-warning-face ((t (:inherit error :foreground "Pink" :weight bold))))
 '(fringe ((t (:background "#232323"))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width 1 :color "#0498da") :foreground "#0498da" :background "#000000"))))
 '(mode-line-buffer-id ((t (:foreground "#0498da" :weight bold))))
 '(isearch ((t (:background "#042028" :foreground "#a57705" :inverse-video t))))
 '(match ((t (:background "#555577" :foreground "#ffc66d"))))
 '(lazy-highlight ((t (:background "#042028" :foreground "#259185" :inverse-video t))))
 '(mode-line-inactive ((t (:weight light :foreground "grey80" :background "grey10" :inherit mode-line))))
 '(mmm-output-submode-face ((t (:background "#530610"))))
 '(mmm-code-submode-face ((t (:background "#04133B"))))
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "#f8f8f8" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "outline" :family "Monaco")))))

(provide-theme 'my-rails-casts)
